[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "C3HYPspumM3qzGVsdqBU1GFSEeFzdKaxYQWcVa4o7Rwe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jacquelinejoya/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
